# Generated by Django 4.2.17 on 2025-05-04 21:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import magahospital.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receiption',
            fields=[
                ('idno', models.CharField(db_index=True, default=magahospital.models.generate_random_code, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('secondname', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_one',
            fields=[
                ('idno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='magahospital.receiption')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('secondname', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('history', models.TextField(blank=True, null=True)),
                ('lab_tests', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('idno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='magahospital.receiption')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('secondname', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lab_results', models.TextField(null=True)),
            ],
        ),
    ]
