# Generated by Django 6.0.4 on 2026-05-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Doctor', 'Doctor'), ('Lab', 'Lab'), ('Dispense', 'Dispense'), ('Completed', 'Completed')], default='Doctor', max_length=20),
        ),
    ]
