# Generated by Django 6.0.4 on 2026-05-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0002_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Lab', 'Lab'), ('Prescription', 'Prescription'), ('Dispense', 'Dispense'), ('Completed', 'Completed')], default='Doctor', max_length=20),
        ),
    ]
