# Generated by Django 4.2.17 on 2025-05-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0002_alter_lab_idno'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_tests',
            field=models.TextField(null=True),
        ),
    ]
