# Generated by Django 6.0.4 on 2026-05-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0003_chatmessage_alter_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
