# Generated by Django 4.2.17 on 2025-05-04 22:07

from django.db import migrations, models
import django.db.models.deletion
import magahospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0003_lab_history_lab_lab_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='idno',
            field=models.OneToOneField(default=magahospital.models.generate_random_code, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='magahospital.doctor_one'),
        ),
    ]
