# Generated by Django 4.2.17 on 2025-05-04 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0004_alter_lab_idno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='idno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='magahospital.doctor_one'),
        ),
    ]
