# Generated by Django 5.2.7 on 2026-05-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0006_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='medication_given',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.CharField(max_length=255),
        ),
    ]
