# Generated by Django 4.2.17 on 2025-05-08 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0006_med_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense_Medics',
            fields=[
                ('idno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='magahospital.med_prescription')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('secondname', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('history', models.TextField(blank=True, null=True)),
                ('lab_tests', models.TextField(null=True)),
                ('lab_results', models.TextField(null=True)),
                ('medical_prescription', models.TextField(null=True)),
                ('dispense_medication', models.TextField(null=True)),
            ],
        ),
    ]
