# Generated by Django 5.2.7 on 2026-05-17 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0008_doctor_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Lab', 'Lab'), ('Prescription', 'Prescription'), ('Cashier', 'Cashier'), ('Dispense', 'Dispense'), ('Completed', 'Completed')], default='Doctor', max_length=20),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lab_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medication_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='magahospital.visit')),
            ],
        ),
    ]
