# Generated by Django 5.2.7 on 2026-05-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0010_medicinestock_alter_visit_status_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
