# Generated by Django 5.2.7 on 2026-05-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0011_vital_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in CM', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vital',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight in KG', max_digits=5, null=True),
        ),
    ]
