# Generated by Django 5.2.7 on 2026-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0012_alter_vital_height_alter_vital_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='next_step',
            field=models.CharField(choices=[('Lab', 'Send To Laboratory'), ('Cashier', 'Send To Cashier')], default='Cashier', max_length=20),
        ),
    ]
