# Generated by Django 5.2.7 on 2026-05-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0012_alter_vital_height_alter_vital_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='procedure_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='next_step',
            field=models.CharField(choices=[('Lab', 'Send To Laboratory'), ('Cashier', 'Send To Cashier')], default='Cashier', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='procedure_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='procedure_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
