# Generated by Django 5.2.7 on 2026-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0014_doctor_next_step_doctor_procedure_name_and_more'),
    ]

    operations = [
        
    ]
