# Generated by Django 5.2.7 on 2026-05-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0015_doctor_next_step_doctor_procedure_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='next_step',
            field=models.CharField(choices=[('Lab', 'Send To Laboratory'), ('Cashier', 'Send To Cashier')], default='Cashier', max_length=20),
        ),
    ]
