# Generated by Django 5.2.7 on 2026-05-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0016_doctor_next_step'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('Waiting Vital', 'Waiting Vital'), ('Waiting Doctor', 'Waiting Doctor'), ('Waiting Lab', 'Waiting Lab'), ('Doctor Review', 'Doctor Review'), ('Waiting Cashier', 'Waiting Cashier'), ('Dispense', 'Dispense'), ('Completed', 'Completed')], default='Waiting Vital', max_length=20),
        ),
    ]
