# Generated by Django 5.2.7 on 2026-05-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0017_doctor_next_step_alter_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='next_step',
            field=models.CharField(choices=[('Lab', 'Laboratory'), ('Cashier', 'Cashier')], default='Cashier', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('Waiting Vital', 'Waiting Vital'), ('Waiting Doctor', 'Waiting Doctor'), ('Waiting Lab', 'Waiting Lab'), ('Waiting Procedure', 'Waiting Procedure'), ('Doctor Review', 'Doctor Review'), ('Waiting Cashier', 'Waiting Cashier'), ('Dispense', 'Dispense'), ('Completed', 'Completed')], default='Waiting Vital', max_length=20),
        ),
    ]
