# Generated by Django 5.2.7 on 2026-05-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0018_doctor_next_step_alter_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_name',
            field=models.CharField(choices=[('Ultrasound', 'Ultrasound'), ('X-Ray', 'X-Ray'), ('ECG', 'ECG'), ('Physiotherapy', 'Physiotherapy'), ('Injection', 'Injection'), ('Dressing', 'Dressing'), ('Endoscopy', 'Endoscopy'), ('Minor Surgery', 'Minor Surgery')], max_length=100),
        ),
    ]
