# Generated by Django 5.2.7 on 2026-05-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0019_alter_procedure_procedure_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='next_step',
            field=models.CharField(choices=[('Lab', 'Send To Laboratory'), ('Procedure', 'Send To Procedure'), ('Cashier', 'Send To Cashier')], max_length=20),
        ),
    ]
