# Generated by Django 5.2.7 on 2026-05-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0020_alter_doctor_next_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='procedure_images/'),
        ),
    ]
