# Generated by Django 5.2.7 on 2026-05-22 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0021_procedure_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='dispensed_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='medication_given',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magahospital.medicinestock'),
        ),
    ]
