# Generated by Django 5.2.7 on 2026-05-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0022_dispense_dispensed_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='tests',
            field=models.ManyToManyField(blank=True, to='magahospital.test'),
        ),
    ]
