# Generated by Django 5.2.7 on 2026-06-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0023_test_doctor_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
