# Generated by Django 5.2.7 on 2026-06-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0024_test_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dose',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
