# Generated by Django 5.2.7 on 2026-06-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0025_prescription_days_prescription_dose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='adjusted_medications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
