# Generated by Django 5.2.7 on 2026-06-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0027_procedurecatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magahospital.procedurecatalog'),
        ),
    ]
