# Generated by Django 5.2.7 on 2026-06-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0028_alter_procedure_procedure_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='dispensed_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='medication_given',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magahospital.medicinestock'),
        ),
    ]
