# Generated by Django 5.2.7 on 2026-06-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0029_alter_dispense_dispensed_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='Maga Hospital', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('footer_text', models.CharField(blank=True, default='All Rights Reserved.', max_length=255)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Settings',
                'verbose_name_plural': 'Hospital Settings',
            },
        ),
    ]
