# Generated by Django 5.2.7 on 2026-06-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magahospital', '0030_hospitalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
